language: ruby

rvm:
  - 2.3

cache:
  bundler: true
  directories:
  # Cache the Onebox data and views to speed up tests
  - tmp/cache/onebox-data
  - tmp/cache/onebox-views
  - spec/dummy/tmp/cache/onebox-data
  - spec/dummy/tmp/cache/onebox-views

bundler_args: --path ../../vendor/bundle --without debug
gemfile:
  - spec/gemfiles/rails_4_2.gemfile
  - spec/gemfiles/rails_5_0.gemfile

env:
  matrix:
  # Username and password from http://docs.travis-ci.com/user/database-setup/
  - DB=sqlite3
  - DB=mysql2     DB_USERNAME=root     DB_PASSWORD=""
  - DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
  global:
  - COVERAGE=1
  - TRAVIS=1

# Avoid rake here, as the RSpec test task spawns a new process which does not run via bundler.
script:
- bundle exec rspec --format d
- bundle exec rubocop
- bundle exec codeclimate-test-reporter
- MIGRATION_SPEC=1 bundle exec rspec spec/migration

notifications:
  slack:
    secure: bnoj7Q/2yA3gtJ2IR/YtXrWCGvN7ukHKnhg1oNYJsOYNk0oEMMgjmGnIRrcdxO4peyOid6aKlcMmP7zrOzPEJsN3qAA4UUCRGq0TgZ2RDMX1sRZ8NN/xCyt84WU9aEtTF0V1hUyG/OaQ7G65XN/XuwJGzw6VDSZE54FSdR/5/eQ=

dist: trusty
sudo: required
