# i18n-tasks finds and manages missing and unused translations
# See https://github.com/glebm/i18n-tasks/blob/master/templates/config/i18n-tasks.yml

# Do not consider these keys missing:
ignore_missing:
# The kaminari gem keys
- views.pagination.*
